### PR TITLE
Theoretical Auto Layout Improvement

### PR DESCRIPTION
**Pull request by DevAndArtist**
According to the docs (https://developer.apple.com/reference/uikit/nslayoutconstraint/1526955-activate) `class func activate(_:)` is an improvement over `.isActive = true`.

### CODE REVIEW

**Comment by DevAndArtist** [comment]
Just noticed from the diff, I'm using tabs 😅

**Comment by JohnSundell** [comment]
Thanks for this @DevAndArtist! Like you say, the change is using tabs. Can you please convert to spaces before I can merge this in? 😇

**Comment by DevAndArtist** [comment]
@JohnSundell done.

**Review by JohnSundell — APPROVED** [review]
Awesome 🚀

**Pull request merged**
